# Generated by Django 4.1 on 2022-09-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_pedido', models.DateTimeField(auto_now_add=True)),
                ('status_pagamento', models.CharField(choices=[('A', 'Aguardando'), ('C', 'Cancelado'), ('P', 'Pago')], default='STATUS_AGUARDANDO', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='loja.pedido')),
                ('preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preco_pedido', to='loja.produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='loja.produto')),
            ],
        ),
    ]
