# Generated by Django 4.1 on 2022-09-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_pedidoitem_qtd_alter_pedidoitem_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='item_escolhido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='loja.produto'),
            preserve_default=False,
        ),
    ]
