# Generated by Django 4.1 on 2022-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosses',
            name='loot',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
