# Generated by Django 4.1 on 2022-09-28 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_endereco',
        ),
        migrations.AddField(
            model_name='conta',
            name='conta_ativa',
            field=models.CharField(choices=[('A', 'A'), ('N', 'N')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cliente_emprestou',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_emprestou', to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cliente_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_pedido', to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_pagamento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrato',
            name='emprestimo_feito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.emprestimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrato',
            name='fatura_obtida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.fatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrato',
            name='transacao_feita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.transacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorito',
            name='cliente_favoritado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagemprestimo',
            name='emprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimo', to='backend.emprestimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagemprestimo',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagemprestimo',
            name='parcelas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_conta',
            field=models.CharField(choices=[('N', 'Normal'), ('G', 'Gold'), ('P', 'Platinum')], max_length=1),
        ),
    ]
