# Generated by Django 4.1 on 2022-10-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_conta_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
