# Generated by Django 4.1 on 2022-09-09 19:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0002_bosses_loot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosses',
            name='boss_image',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='%y/%m/%d', variations={}),
            preserve_default=False,
        ),
    ]
