# Generated by Django 4.1 on 2022-09-29 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cartao', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField()),
                ('cliente_emprestou', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_emprestou', to='backend.cliente')),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_pedido', to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=100)),
                ('tipo_conta', models.CharField(choices=[('N', 'Normal'), ('G', 'Gold'), ('P', 'Platinum')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transacao', models.CharField(choices=[('TE', 'TE'), ('DO', 'DO'), ('BO', 'BO'), ('VO', 'VO'), ('DU', 'DU')], max_length=2)),
                ('data_transacao', models.DateField()),
                ('valor_transferido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('beneficiado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiado', to='backend.cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PagEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.IntegerField()),
                ('juros', models.DecimalField(decimal_places=2, max_digits=2)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimo', to='backend.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_favoritado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parcelas', models.IntegerField()),
                ('data_pagamento', models.DateField()),
                ('status_pagamento', models.CharField(choices=[('P', 'P'), ('NP', 'NP')], max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emprestimo_feito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.emprestimo')),
                ('fatura_obtida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.fatura')),
                ('transacao_feita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.transacao')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carteira', models.DecimalField(decimal_places=5, max_digits=20)),
                ('conta_ativa', models.CharField(choices=[('A', 'A'), ('N', 'N')], max_length=1)),
                ('cartao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartao', to='backend.cartao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente'),
        ),
    ]
