# Generated by Django 4.1 on 2022-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cliente_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('?', '?')], max_length=1),
        ),
    ]
