# Generated by Django 4.1 on 2022-10-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_cartao_cliente_cartao_limite_cliente_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='carteira',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
